Browser -> SERVER: Request Https
SERVER -> Browser: Responce Https
|||
LOOP  5 minutes interval
SERVER -> Sakura.io: Request Websocket
Sakura.io -> IOTmodule: Request LTE
IOTmodule -> ghf_SensorUnit1..8: Request modbus.RS485
Note right of Sakura.io: Secure private network
ghf_SensorUnit1..8 -> IOTmodule: Response modbus.RS485
IOTmodule -> Sakura.io: Responce LTE
Sakura.io -> SERVER: Responce Websocket
SERVER -> SERVER: Data storage
end
|||
