Browser -> SERVER: Request Https
SERVER -> Browser: Responce Https
SERVER -> Sakura.io: Request Websocket
Sakura.io -> IOTmodule: Request LTE
Note over SERVER,Sakura.io: LOOP \n5minute interval
IOTmodule -> ghf_SensorUnit1..8: Request modbus.RS485
Note right of Sakura.io: Secure private network
ghf_SensorUnit1..8 -> IOTmodule: Response modbus.RS485
IOTmodule -> Sakura.io: Responce LTE
Sakura.io -> SERVER: Responce Websocket
